-- This file can be generated by opening the block design,
-- right-clicking on the .bd file, and selecting
-- "Create HDL Wrapper". In the opening dialog, select
-- "Let Vivado manage wrapper and auto-update".

--Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
--Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
----------------------------------------------------------------------------------
--Tool Version: Vivado v.2025.2 (lin64) Build 6299465 Fri Nov 14 12:34:56 MST 2025
--Date        : Thu Jun 11 20:43:18 2026
--Host        : henry-PC running 64-bit Ubuntu 24.04.4 LTS
--Command     : generate_target system_wrapper.bd
--Design      : system_wrapper
--Purpose     : IP block netlist
----------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;
entity system_wrapper is
  port (
    pcie_clkin_clk_n : in STD_LOGIC_VECTOR ( 0 to 0 );
    pcie_clkin_clk_p : in STD_LOGIC_VECTOR ( 0 to 0 );
    pcie_mgt_rxn : in STD_LOGIC_VECTOR ( 3 downto 0 );
    pcie_mgt_rxp : in STD_LOGIC_VECTOR ( 3 downto 0 );
    pcie_mgt_txn : out STD_LOGIC_VECTOR ( 3 downto 0 );
    pcie_mgt_txp : out STD_LOGIC_VECTOR ( 3 downto 0 );
    pcie_reset : in STD_LOGIC
  );
end system_wrapper;

architecture STRUCTURE of system_wrapper is
  component system is
  port (
    pcie_mgt_rxn : in STD_LOGIC_VECTOR ( 3 downto 0 );
    pcie_mgt_rxp : in STD_LOGIC_VECTOR ( 3 downto 0 );
    pcie_mgt_txn : out STD_LOGIC_VECTOR ( 3 downto 0 );
    pcie_mgt_txp : out STD_LOGIC_VECTOR ( 3 downto 0 );
    pcie_clkin_clk_n : in STD_LOGIC_VECTOR ( 0 to 0 );
    pcie_clkin_clk_p : in STD_LOGIC_VECTOR ( 0 to 0 );
    pcie_reset : in STD_LOGIC
  );
  end component system;
begin
system_i: component system
     port map (
      pcie_clkin_clk_n(0) => pcie_clkin_clk_n(0),
      pcie_clkin_clk_p(0) => pcie_clkin_clk_p(0),
      pcie_mgt_rxn(3 downto 0) => pcie_mgt_rxn(3 downto 0),
      pcie_mgt_rxp(3 downto 0) => pcie_mgt_rxp(3 downto 0),
      pcie_mgt_txn(3 downto 0) => pcie_mgt_txn(3 downto 0),
      pcie_mgt_txp(3 downto 0) => pcie_mgt_txp(3 downto 0),
      pcie_reset => pcie_reset
    );
end STRUCTURE;
